spring.application.name=restaurant-service
server.port=8085
eureka.client.enableJersey=false
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://food:food@eureka:8761/eureka/
#  my sql  properties
spring.datasource.url=jdbc:mysql://mysql:3306/Food_Application_Platform?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Krishna@81433*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.bootstrap-servers=kafka:9092



jwt.secret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=food
spring.security.user.password=food
