spring.application.name=notification-service
server.port=8282
eureka.client.enableJersey=false
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.enabled=true
#eureka.client.service-url.defaultZone=http://food:food@localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://food:food@eureka:8761/eureka/
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.security.user.name=food
spring.security.user.password=food
