spring.application.name=user-authentication-service
server.port=8086
#spring.datasource.url=jdbc:mysql://localhost:3306/Food_Application_Platform?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://mysql:3306/Food_Application_Platform?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Krishna@81433*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
eureka.client.enableJersey=false
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://food:food@eureka:8761/eureka/
jwt.secret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.security.user.name=food
spring.security.user.password=food
google.client.id=214785903268-38u5f7t39am52miefl2o9rbrl19bulam.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8086/google/callback





