# ====================================================
# DeliveryService - Service-Specific Config
# ====================================================
server:
  port: 8181

spring:
  application:
    name: DeliveryService
