# ====================================================
# NotificationService - Service-Specific Config
# ====================================================
server:
  port: 8282

spring:
  application:
    name: notification-service
