spring.application.name=api-gateway-service
server.port=9000
eureka.client.enableJersey=false
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://food:food@localhost:8761/eureka/
spring.security.user.name=food
spring.security.user.password=food
